const Map<String, Map<String, String>> translations = {
  'en': {
    'appTitle': 'Kisaan Mitra',
    'welcome': 'Welcome!',
    'selectPlant': 'Select a plant to identify pests by symptoms.',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'analyzeSymptoms': 'Analyze Symptoms',
    'symptomAnalysis': 'Symptom Analysis',
    'confidence': 'Confidence:',
    'identifyPests': 'Identify Pests & Get Action Plan',
    'pestActionPlan': 'Pest & Action Plan',
    'plant_tomato': 'Tomato',
    'plant_potato': 'Potato',
    'plant_grape': 'Grape',
    'plant_corn': 'Corn',
    'plant_wheat': 'Wheat',
    'plant_sugarcane': 'Sugarcane',
    'scanTitle': 'Pest & Symptom Scan',
  },
  'hi': {
    'appTitle': 'किसान मित्र',
    'welcome': 'आपका स्वागत है!',
    'selectPlant': 'लक्षणों से कीटों की पहचान के लिए एक पौधा चुनें।',
    'camera': 'कैमरा',
    'gallery': 'गैलरी',
    'analyzeSymptoms': 'लक्षणों का विश्लेषण करें',
    'symptomAnalysis': 'लक्षण विश्लेषण',
    'confidence': 'आत्मविश्वास:',
    'identifyPests': 'कीटों की पहचान करें और कार्य योजना प्राप्त करें',
    'pestActionPlan': 'कीट और कार्य योजना',
    'plant_tomato': 'टमाटर',
    'plant_potato': 'आलू',
    'plant_grape': 'अंगूर',
    'plant_corn': 'मक्का',
    'plant_wheat': 'गेहूँ',
    'plant_sugarcane': 'गन्ना',
    'scanTitle': 'कीट और लक्षण स्कैन',
  },
};